// Generated by CoffeeScript 1.6.3
(function() {
  var clearElement, inputEl, renderItem, renderList, todoList;

  todoList = function() {
    this.todos = [];
    return this;
  };

  todoList.prototype.add = function(todo) {
    return this.todos.push(todo);
  };

  todoList.prototype.find = function(item) {
    return this.todos.filter(function(i) {
      return i.task === item;
    });
  };

  todoList.prototype.toggle = function(todo) {
    return todo.done = !todo.done;
  };

  clearElement = function(el) {
    el.innerHTML = '';
    return el.value = '';
  };

  renderItem = function(el, item) {
    var newNode;
    newNode = document.createElement('li');
    newNode.innerText = item.task;
    newNode.className = item.done ? 'completed' : 'incomplete';
    return el.appendChild(newNode);
  };

  renderList = function(list) {
    var item, listEl, _i, _len, _ref, _results;
    listEl = document.getElementById('list');
    clearElement(listEl);
    _ref = list.todos;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      _results.push(renderItem(listEl, item));
    }
    return _results;
  };

  window.list = new todoList();

  list.add({
    'task': 'hello mom',
    'done': false
  });

  renderList(list);

  inputEl = document.getElementById('todo-input');

  document.getElementById('add-button').addEventListener('click', function(e) {
    if (inputEl.value.length) {
      list.add({
        'task': inputEl.value,
        'done': false
      });
      clearElement(inputEl);
      return renderList(list);
    }
  });

  document.getElementById('list').addEventListener('click', function(e) {
    list.toggle(list.find(e.target.innerText)[0]);
    return renderList(list);
  });

}).call(this);
